"""empty message

Revision ID: 9edd1b8b4b08
Revises: dd02e78063e2
Create Date: 2017-09-19 23:39:21.261231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9edd1b8b4b08'
down_revision = 'dd02e78063e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('private', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story', 'private')
    # ### end Alembic commands ###
