"""empty message

Revision ID: f8f05128a604
Revises: aacc1c672363
Create Date: 2017-09-15 15:56:49.107355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8f05128a604'
down_revision = 'aacc1c672363'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('story_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story', 'story_id')
    # ### end Alembic commands ###
